services:
    eles.coreframe.listener:
        class: eles\coreframe\event\listener
        arguments:
            - @dbal.conn
            - @service_container
            - @cache.driver
            - @config
            - @config_text
            - @controller.helper
            - @request
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }

    eles.coreframe.widgets_service:
        class: eles\coreframe\inc\widgets_service
        arguments:
            - @dbal.conn
            - @config
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%
